### ISSUE TITLE
Attribute error Module 'CV2' has no attribute createLBPHFaceRecognizer

### ISSUE THREAD

**Issue by guruvishnuvardan** [thecodacus/Face-Recognition#3]
Hi,

I have Installed OpenCV 3.3 and OpenCV Contrib (with out CUDA), Can you please help me to resolve this defect. Also, Can you please suggest me, If there is anything wrong in installing OpenCV_Contrib 

![open_contrib_error](https://user-images.githubusercontent.com/31349523/30313272-601530ce-97ba-11e7-8c24-ed5c60eaebbd.png)

**Comment by pomaranczowykoles** [comment]
change to
recognizer = cv2.face.LBPHFaceRecognizer_create()
recognizer.read('trainer/trainer.yml')

**Comment by thecodacus** [comment]
I guessing the issue is resolved so closing it

**Comment by hunaidkhan2000** [comment]
AttributeError: module 'cv2.cv2' has no attribute 'face', after trying above recognizer = cv2.face.LBPHFaceRecognizer_create() . still getting error

**Comment by am-becker** [comment]
same. I am also getting the above error.
I have opencv-contrib-python installed as well.

**Comment by Rich2020** [comment]
Same here.

**Comment by am-becker** [comment]
I fixed this issue with two commands:
First: 
sudo pip3 uninstall opencv-contrib-python
Second:
sudo python3 -m pip install opencv-contrib-python==3.3.0.9
This fixed my issues. Hope it helps somebody!
Also, if you are using python2, replace “pip3” with “pip” and “python3” with “python”

**Comment by Rich2020** [comment]
Using IntelliJ, I created a new virtual environment and installed the opencv and contrib libraries; this fixed it.

**Comment by naren-sai-krishna** [comment]
Thanks a lot @aaroexxt ... It worked for me .

**Comment by shwetabh12** [comment]
![Screenshot from 2019-03-09 21-04-15](https://user-images.githubusercontent.com/31704502/54073588-33f64b80-42af-11e9-871f-f6469eda2b74.png)
As I am running on jupyter notebook on Kaggle platform ,How to  get rid of these error .

**Comment by Priyanknasit** [comment]
> ![Screenshot from 2019-03-09 21-04-15](https://user-images.githubusercontent.com/31704502/54073588-33f64b80-42af-11e9-871f-f6469eda2b74.png)
> As I am running on jupyter notebook on Kaggle platform ,How to get rid of these error .

use this..
pip install opencv-contrib-python --upgrade

**Comment by maanyapathak** [comment]
there is what worked for me i had installed opencv-python but  not  opencv-contrib-python so when i installed opencv-contrib-python it worked i didn;t even needed to uninstall opencv-python
